engine/src/Emercoin/OAuthBundle/Entity/Client.php
<?php

namespace Emercoin\OAuthBundle\Entity;

use FOS\OAuthServerBundle\Entity\Client as BaseClient;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity()
 */
class Client extends BaseClient
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", nullable=false)
     *
     * @Assert\NotBlank()
     */
    protected $name;

    /**
     * @var User
     *
     * @ORM\ManyToOne(targetEntity="Emercoin\OAuthBundle\Entity\User", inversedBy="clients", fetch="EAGER")
     * @ORM\JoinColumn(name="user", onDelete="CASCADE", nullable=false)
     */
    protected $user;

    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Client
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    public function getClientId()
    {
        return $this->id.'_'.$this->getRandomId();
    }

    /**
     * Set user
     *
     * @param User $user
     * @return Client
     */
    public function setUser(User $user)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return User
     */
    public function getUser()
    {
        return $this->user;
    }
}

engine/src/Emercoin/OAuthBundle/Form/ClientType.php
<?php

namespace Emercoin\OAuthBundle\Form;

use Emercoin\OAuthBundle\Entity\Client;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints as Assert;

class ClientType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $user = $options['user'];

        $builder
            ->add(
                'name',
                null,
                array(
                    'label' => 'App Name',
                )
            )
            ->add(
                'redirect_uris',
                CollectionType::class,
                array(
                    'label' => 'Redirect URIs',
                    'entry_type' => UrlType::class,
                    'entry_options' => array(
                        'label' => false,
                        'default_protocol' => 'https',
                        'constraints' => array(
                            new Assert\Url(array('protocols' => array('http', 'https'))),
                        ),
                    ),
                    'prototype' => true,
                    'allow_add' => true,
                    'allow_delete' => true,
                    'delete_empty' => true,
                    'by_reference' => false,
                )
            )->addEventListener(
                FormEvents::POST_SUBMIT,
                function (FormEvent $event) use ($user) {
                    $form = $event->getForm();
                    /** @var Client $data */
                    $data = $form->getData();
                    $data->setUser($user);
                }
            );
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            array(
                'data_class' => 'Emercoin\OAuthBundle\Entity\Client',
                'user' => null,
                'attr' => array('novalidate' => 'novalidate'),
            )
        );
        $resolver->setAllowedTypes('user', array('Symfony\Component\Security\Core\User\AdvancedUserInterface'));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'emercoin_client';
    }
}

engine/src/Emercoin/OAuthBundle/Controller/ClientController.php
<?php

namespace Emercoin\OAuthBundle\Controller;

use Emercoin\OAuthBundle\Entity\Client;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

/**
 * Client controller.
 *
 * @Route("/client")
 */
class ClientController extends Controller
{
    /**
     * Lists all client entities.
     *
     * @Route("s", name="client_index")
     * @Method("GET")
     * @Template()
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $clients = $em->getRepository('EmercoinOAuthBundle:Client')->findBy(
            ['user' => $this->getUser()],
            ['id' => 'desc']
        );

        return array(
            'clients' => $clients,
        );
    }

    /**
     * Creates a new client entity.
     *
     * @Route("/new", name="client_new")
     * @Method({"GET", "POST"})
     * @Template()
     */
    public function newAction(Request $request)
    {
        $client = new Client();
        $form = $this->createForm('Emercoin\OAuthBundle\Form\ClientType', $client, array('user' => $this->getUser()));
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($client);
            $em->flush($client);

            return $this->redirectToRoute('client_index');
        }

        return array(
            'client' => $client,
            'form' => $form->createView(),
        );
    }

    /**
     * Displays a form to edit an existing client entity.
     *
     * @Route("/{id}/edit", name="client_edit")
     * @Method({"GET", "POST"})
     * @Template()
     */
    public function editAction(Request $request, $id)
    {
        $client = $this->getDoctrine()->getRepository('EmercoinOAuthBundle:Client')->findOneBy(
            ['user' => $this->getUser(), 'id' => $id]
        );
        if (!$client) {
            throw new NotFoundHttpException();
        }
        $deleteForm = $this->createDeleteForm($client);
        $editForm = $this->createForm(
            'Emercoin\OAuthBundle\Form\ClientType',
            $client,
            array('user' => $this->getUser())
        );
        $editForm->handleRequest($request);

        if ($editForm->isSubmitted() && $editForm->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('client_edit', array('id' => $client->getId()));
        }

        return array(
            'client' => $client,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Deletes a client entity.
     *
     * @Route("/{id}", name="client_delete")
     * @Method("DELETE")
     */
    public function deleteAction(Request $request, $id)
    {
        $client = $this->getDoctrine()->getRepository('EmercoinOAuthBundle:Client')->findOneBy(
            ['user' => $this->getUser(), 'id' => $id]
        );
        if (!$client) {
            throw new NotFoundHttpException();
        }

        $form = $this->createDeleteForm($client);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($client);
            $em->flush($client);
        }

        return $this->redirectToRoute('client_index');
    }

    /**
     * Creates a form to delete a client entity.
     *
     * @param Client $client The client entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm(Client $client)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('client_delete', array('id' => $client->getId())))
            ->setMethod('DELETE')
            ->add('delete', SubmitType::class, array('attr' => array('onclick' => 'return confirm(\'Are you sure?\')')))
            ->getForm();
    }
}

engine/src/Emercoin/OAuthBundle/Resources/views/Client/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h2>App edit</h2>

    {{ form_start(edit_form) }}
    {{ form_widget(edit_form) }}
    <div>
        <button id="add-another-uri">Add URI</button>
    </div>
    <input type="submit" value="Submit"/>
    {{ form_end(edit_form) }}
    <div>
        {{ form_start(delete_form) }}
        {{ form_end(delete_form) }}
    </div>
    <div>
        <a href="{{ path('client_index') }}">Back to the list</a>
    </div>
{% endblock %}

{% block javascripts %}
    <script>
        var uriCount = '{{ edit_form.redirect_uris|length }}';
        jQuery(document).ready(function () {
            jQuery('#emercoin_client_redirect_uris').wrapInner('<ul></ul>');
            jQuery('#add-another-uri').click(function (e) {
                e.preventDefault();
                var prototype = jQuery('#emercoin_client_redirect_uris')
                var uriList = prototype.find('ul');
                var newWidget = prototype.attr('data-prototype');
                newWidget = newWidget.replace(/__name__/g, uriCount);
                uriCount++;
                var newLi = jQuery('<li></li>').html(newWidget);
                newLi.appendTo(uriList);
            });
        });
    </script>
{% endblock javascripts %}

engine/src/Emercoin/OAuthBundle/Resources/views/Client/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h2>My Apps</h2>
    <table border="1px" cellpadding="10px" cellspacing="0">
        <thead>
        <tr>
            <th>App Name</th>
            <th>Client Id</th>
            <th>Secret</th>
            <th>URIs</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for client in clients %}
            <tr>
                <td>{{ client.name }}</td>
                <td>{{ client.clientId }}</td>
                <td>{{ client.secret }}</td>
                <td>
                    <ul style="padding: 0; margin: 0;">
                        {% for uri in client.redirectUris %}
                            <li>{{ uri }}</li>
                        {% endfor %}
                    </ul>
                </td>
                <td>
                    <div>
                        <a href="{{ path('client_edit', { 'id': client.id }) }}">edit</a>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <ul style="list-style: none; padding: 0;">
        <li>
            <a href="{{ path('client_new') }}">Create a new App</a>
        </li>
    </ul>
{% endblock %}

engine/src/Emercoin/OAuthBundle/Resources/views/Client/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>App creation</h1>

    {{ form_start(form) }}
    {{ form_widget(form) }}
    <div>
        <button id="add-another-uri">Add URI</button>
    </div>
    <input type="submit" value="Create"/>
    {{ form_end(form) }}

    <div>
        <a href="{{ path('client_index') }}">Back to the list</a>
    </div>
{% endblock body %}

{% block javascripts %}
    <script>
        var uriCount = '{{ form.redirect_uris|length }}';
        jQuery(document).ready(function () {
            jQuery('#emercoin_client_redirect_uris').wrapInner('<ul></ul>');
            jQuery('#add-another-uri').click(function (e) {
                e.preventDefault();
                var prototype = jQuery('#emercoin_client_redirect_uris')
                var uriList = prototype.find('ul');
                var newWidget = prototype.attr('data-prototype');
                newWidget = newWidget.replace(/__name__/g, uriCount);
                uriCount++;
                var newLi = jQuery('<li></li>').html(newWidget);
                newLi.appendTo(uriList);
            });
        });
    </script>
{% endblock javascripts %}